### ISSUE TITLE
super error

### ISSUE THREAD

**Issue by gildo** [defunkt/tomdoc#6]
tomdoc =>  gem build tomdoc.gemspec

```
Invalid gemspec in [tomdoc.gemspec]: RubyGem version error: RubyInline(3.8.6 not = 3.7.0)

ERROR:  While executing gem ... (NoMethodError)
    undefined method `mark_version' for nil:NilClas
```

**Comment by trans** [comment]
The missing `mark_version` throws me off a bit here. Is this issue resolved by easing the version constraint on RubyInline?

**Comment by gildo** [comment]
Nope

**Comment by trans** [comment]
Damn. Ok I will have to look at the problem in more detail. If you have any insight into a fix, please let me know. I'd like to get a new release of TomDoc out as soon as possible.

**Comment by gildo** [comment]
`➜  tomdoc git:(tomdoc.rb) gem build tomdoc.gemspec 
`internal:lib/rubygems/custom_require:29:in `require': no such file to load -- tomdoc/version (LoadError)
`from internal:lib/rubygems/custom_require:29:in `require'
`from tomdoc.gemspec:1:in `load'
`from /usr/lib/ruby/1.9.1/rubygems/specification.rb:508:in `eval'
`from /usr/lib/ruby/1.9.1/rubygems/specification.rb:508:in `load'
`from /usr/lib/ruby/1.9.1/rubygems/commands/build_command.rb:43:in `load_gemspecs'
`from /usr/lib/ruby/1.9.1/rubygems/commands/build_command.rb:21:in `execute'
`from /usr/lib/ruby/1.9.1/rubygems/command.rb:270:in `invoke'
`from /usr/lib/ruby/1.9.1/rubygems/command_manager.rb:134:in `process_args'
`from /usr/lib/ruby/1.9.1/rubygems/command_manager.rb:104:in `run'
`from /usr/lib/ruby/1.9.1/rubygems/gem_runner.rb:58:in `run'
`from /usr/bin/gem:21:in `<main>'
`➜  tomdoc git:(tomdoc.rb)

**Comment by trans** [comment]
Ah, okay. This is about building the tomdoc gem. I adjusted the require statement in the gemspec and pushed the changes.

**Comment by gildo** [comment]
@trans, try this => https://github.com/fyskij/tomdoc/commit/2bff62c4b5caad4a05b0203c033d13e84969de6d

error: https://gist.github.com/974731

**Comment by trans** [comment]
Thanks. Added that too.

**Comment by gildo** [comment]
ok fixed, time to close the issue

**Comment by trans** [comment]
thanks fyskij

**Comment by gildo** [comment]
np :)
